#!/bin/bash

cd ~/
#============= Installing dependencies ================
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install subversion cmake wget net-tools nano
#======================================================

#=========== Installing kernel modules ================
sudo apt -y install linux-headers-$(uname -r)
#======================================================

#=================== Networking ======================
cd ~/vbbu1/cu
source cu_net_conf
#======================================================

#================== Building OAI ======================
cd ~/vbbu1/cu
source cu_build
#======================================================

#================= Configuring OAI ====================
cd ~/vbbu1/cu
source cu_conf
#======================================================

#sudo ./cmake_targets/lte_build_oai/build/lte-softmodem -O ci-scripts/conf_files/cu/rcc.band7.tm1.if4p5.50PRB.conf
