#!/bin/bash

cd ~/
#================== Building OAI ======================
#Getting source code
git clone https://andresocp@gitlab.eurecom.fr/oai/openairinterface5g.git

#cloning conf files
mkdir openairinterface5g/ci-scripts/conf_files/cu

cd ~/openairinterface5g/
git checkout -f v1.1.1
source oaienv  

#Installing dependencies
./cmake_targets/build_oai -I 
#building the code
./cmake_targets/build_oai --eNB -c






