#!/bin/bash
source cu_params
cp ~/openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF/rcc.band7.tm1.50PRB.nfapi.conf ~/openairinterface5g/ci-scripts/conf_files/cu
PREFIX=$HOME'/openairinterface5g/ci-scripts/conf_files/cu/rcc.band7.tm1.50PRB.nfapi.conf'
#cp ~/openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF/rcc.band7.tm1.50PRB.nfapi.conf /home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/vbbu2/cu
#PREFIX='/home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/vbbu2/cu/rcc.band7.tm1.50PRB.nfapi.conf'


#==================== CU eNB ID  ======================
sed -i '/eNB_ID/c\    eNB_ID    =  '$eNB_ID';' $PREFIX
sed -i '/Nid_cell					      = /c\      Nid_cell					      = '$Nid_cell';' $PREFIX
sed -i '/_mbsfn/c\      Nid_cell_mbsfn          			      = '$Nid_cell_mbsfn';' $PREFIX
#======================================================

#====================== CU PLMN  ======================
sed -i '/tracking_area_code = 1/c\    tracking_area_code = '$tac';' $PREFIX
sed -i '/plmn_list/c\    plmn_list = ( { mcc = '$mcc'; mnc = '$mnc'; mnc_length = 2; } )' $PREFIX
#======================================================

#====================== TX/RX CU ======================
sed -i '/downlink_frequency/c\      downlink_frequency      			      = '$downlink_frequency';'   $PREFIX
sed -i '/eutra_band/c\      eutra_band              			      = '$eutra_band';'   $PREFIX
sed -i '/N_RB_DL/c\      N_RB_DL                 			      = '$N_RB_DL';'   $PREFIX
#======================================================


#================== CU/DU interfaces ==================
sed -i '/local_s_if_name/c\	local_s_if_name  = "'$cu_if_name'";' $PREFIX
sed -i '/remote_s_address/c\	remote_s_address = "'$du_ip'";' $PREFIX
sed -i '/local_s_address/c\	local_s_address  = "'$cu_ip'";' $PREFIX
sed -i '/local_s_portc/c\	local_n_portc    = "'$local_s_portc'";' $PREFIX
sed -i '/remote_s_portc/c\	remote_n_portc    = "'$remote_s_portc'";' $PREFIX
sed -i '/local_s_portd/c\	local_n_portd    = "'$local_s_portd'";' $PREFIX
sed -i '/remote_s_portd/c\	remote_n_portd    = "'$remote_s_portd'";' $PREFIX

#======================================================

#================== MME parameters ====================
sed -i '/mme_ip_address/c\    mme_ip_address      = ( { ipv4       =  "'$mme_ip'";' $PREFIX
#======================================================

#================ NETWORK_INTERFACES ==================
sed -i '/ENB_INTERFACE_NAME_FOR_S1_MME/c\        ENB_INTERFACE_NAME_FOR_S1_MME            = "'$cu_if_s1c'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_S1_MME/c\        ENB_IPV4_ADDRESS_FOR_S1_MME              = "'$cu_ip_s1c'";' $PREFIX
sed -i '/ENB_INTERFACE_NAME_FOR_S1U/c\        ENB_INTERFACE_NAME_FOR_S1U               = "'$cu_if_s1u'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_S1U/c\        ENB_IPV4_ADDRESS_FOR_S1U                 = "'$cu_ip_s1u'";' $PREFIX
sed -i '/ENB_PORT_FOR_S1U/c\        ENB_PORT_FOR_S1U                         = "'$cu_port_s1u'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_X2C/c\        ENB_IPV4_ADDRESS_FOR_X2C                 = "'$cu_ip_x2c'";' $PREFIX
sed -i '/ENB_PORT_FOR_X2C/c\      ENB_PORT_FOR_X2C              = "'$cu_port_x2c'";' $PREFIX
#======================================================
