#!/bin/bash

#================= General parameters ==================
#PLMN
tac=600
mcc=208
mnc=92
eNB_ID=0xe02
Nid_cell=2
Nid_cell_mbsfn=2

#================= General interfaces ==================
#Networking
mme_ip=192.168.247.102
spgw_ip=192.168.248.159
local_if_name=eth0
local_ip_net=10.0.3.1
#=======================================================

#================== CU/DU interfaces ===================
cu_if_name=$local_if_name:1
cu_ip=10.0.20.10
du_ip=10.0.20.20
local_s_portc=50001
remote_s_portc=50000
local_s_portd=50011
remote_s_portd=50010 
#=======================================================

#==================== CU interfaces ====================
cu_if_s1c=$local_if_name:2
cu_ip_s1c=192.168.247.20
cu_if_s1u=$local_if_name:3
cu_ip_s1u=192.168.248.20
cu_port_s1u=2152
cu_if_x2c=$local_if_name:4
cu_ip_x2c=192.168.249.20
cu_port_x2c=36422
#=======================================================

#================== TX/RX parameters ===================
eutra_band=7
N_RB_DL=25
downlink_frequency=2680000000L
#=======================================================


