#!/bin/bash
sudo modprobe sctp #allow sctp flows

cu_host_if_name=enx0050b6a8ba4e
lxc_if_name=lxcbr0
lxc_ip=10.0.3.1


#=================== Routes to EPC =====================
epc_host_ip=192.168.209.2
mme_ip=192.168.247.102
spgw_ip=192.168.248.159
#adding route to EPC S1C interface
sudo ip route add $mme_ip via $epc_host_ip dev $cu_host_if_name
#adding route to EPC S1U interface
sudo ip route add $spgw_ip via $epc_host_ip dev $cu_host_if_name
#======================================================

#=================== Routes to DU =====================
du_host_ip=192.168.209.20
du_ip=10.0.20.20
#adding route to DU 
sudo ip route add $du_ip via $du_host_ip dev $cu_host_if_name
#======================================================


#============== Routes to CU container ================
cu_ip_s1c=192.168.247.20
cu_ip_s1u=192.168.248.20
cu_ip_x2c=192.168.249.20
cu_ip=10.0.20.10
#adding route to CU S1C interface
sudo ip route add $cu_ip_s1c via $lxc_ip dev $lxc_if_name
#adding route to CU S1U interface
sudo ip route add $cu_ip_s1u via $lxc_ip dev $lxc_if_name
#adding route to CU X2C interface
sudo ip route add $cu_ip_x2c via $lxc_ip dev $lxc_if_name
#adding route to CU 
sudo ip route add $cu_ip via $lxc_ip dev $lxc_if_name
#======================================================
