#!/bin/bash
##------------ Installing OAI and dependencies  --------------
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install subversion git cmake nano wget

##------------ Installing kernel modules  --------------
sudo apt -y install linux-headers-$(uname -r)

##------------ Building OAI   --------------
#Getting source code
git clone https://andresocp@gitlab.eurecom.fr/oai/openairinterface5g.git

#cloning conf files
mkdir ~/openairinterface5g/ci-scripts/conf_files/DU
cp ~/openairinterface5g/ci-scripts/conf_files/ue.nfapi.conf ~/openairinterface5g/ci-scripts/conf_files/DU
wget -O ~/openairinterface5g/ci-scripts/conf_files/DU/DU_conf.tar.gz https://www.dropbox.com/s/psc7dp0nw455j31/DU.tar.gz?dl=0 
tar -xzf ~/openairinterface5g/ci-scripts/conf_files/DU/DU_conf.tar.gz -C ~/openairinterface5g/ci-scripts/conf_files/DU/DU_conf.tar.gz

cd ~/openairinterface5g/
#Checking out last version of master branch
git checkout -f v1.1.0
#Installing dependencies
./cmake_targets/build_oai -I -w USRP
#building the code
./cmake_targets/build_oai --eNB -w USRP








