#!/bin/bash


usage() { echo "Usage: $0 [-nif | --local_n_if <string>] [-lnip | --local_n_address <string>] [-rnip | --remote_n_address <string>]" 1>&2; exit 1; }

while [ "$1" != "" ]; do
    case $1 in
        -nif | --local_n_if )    		shift
                                		local_n_if_name=$1
		                                ;;
        -lnip | --local_n_address )    	shift
                               			local_n_address=$1
							   			;;
        -rnip | --remote_n_address )    shift
										remote_n_address=$1                                
                               			;;
        * )                    			usage
                               			exit 1
    esac
    shift
done
PREFIX='~/openairinterface5g/ci-scripts/conf_files/ue.nfapi.conf'


##------------ Configuring MACRLC  --------------
sed -i '/local_n_if_name/c\	local_n_if_name  = "'$local_n_if_name'";' $PREFIX
sed -i '/remote_n_address/c\	remote_n_address = "'$remote_n_address'";' $PREFIX
sed -i '/local_n_address/c\	local_n_address  = "'$local_n_address'";' $PREFIX

