#!/bin/bash

#installing lxc
stty -echo
read -p "Password: " pass
stty echo
#echo $pass | sudo -S apt update
echo $pass | sudo -S lxc-create -t download -n nFAPI_DU -- -d ubuntu -r bionic -a amd64
sudo -s chroot /var/lib/lxc/nFAPI_DU/rootfs/ passwd  ubuntu 
sudo -s  wget -O /var/lib/lxc/nFAPI_DU/rootfs/home/ubuntu/DU_conf.tar.gz https://www.dropbox.com/s/psc7dp0nw455j31/DU.tar.gz?dl=0 
sudo -s tar -xzf /var/lib/lxc/nFAPI_DU/rootfs/home/ubuntu/DU_conf.tar.gz -C /var/lib/lxc/nFAPI_DU/rootfs/home/ubuntu/
sudo lxc-start -n nFAPI_DU -d
sudo lxc-console -n nFAPI_DU






