#!/bin/bash

##------------ Installing dependencies  --------------
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install git subversion cmake nano wget net-tools

##------------ Installing kernel modules  --------------
sudo apt -y install linux-headers-$(uname -r)

##------------ Networking  --------------
#source du_net

##------------ Building OAI --------------
#source DU/du_build

##------------ Configuring OAI --------------
#source cu_conf



