#!/bin/bash

lxc_name=vbbu1
PREFIX='/var/lib/lxc/'$lxc_name'/config'
sudo lxc-create -t download -n $lxc_name -- -d ubuntu -r xenial -a amd64
echo -e  'lxc.cgroup.devices.allow = c 189:* rwm' | sudo -s tee -a $PREFIX
echo -e  'lxc.mount.entry = /dev/bus/usb dev/bus/usb none bind,optional,create=dir' | sudo -s tee -a $PREFIX
sudo lxc-start -n $lxc_name -d
sudo -s lxc-attach -n $lxc_name -- passwd ubuntu
