#!/bin/bash


source du_params
lxc_name=DU_2

PREFIX_LOCAL='/home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/CU_DU_L2_nFAPI/DU/du_params'
PREFIX_REMOTE='/home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/CU_DU_L2_nFAPI/CU/cu_params'
PREFIX_FS='/var/lib/lxc/'$lxc_name'/rootfs/'
PREFIX_HOME='/var/lib/lxc/'$lxc_name'/rootfs/home/ubuntu'
clone_url='https://www.dropbox.com/s/md2fm7b24pinzv8/DU.tar.gz?dl=0'

sudo lxc-create -t download -n $lxc_name -- -d ubuntu -r bionic -a amd64
sudo -s  wget -O $PREFIX_HOME/DU.tar.gz $clone_url
sudo -s tar -xzf $PREFIX_HOME/DU.tar.gz -C $PREFIX_HOME

sudo lxc-start -n $lxc_name -d

lxc_ip=$(sudo -s lxc-info -n $lxc_name --ip | cut -d ":" -f2)
i="0"
while [ $i -lt 20 ] 
do
    sleep 1    
    if [ ! -z "$lxc_ip" ]
    then  
        echo 'local_n_address='$lxc_ip'' | tee -a $PREFIX_LOCAL
        echo 'remote_s_address='$lxc_ip'' | tee -a $PREFIX_REMOTE        
        break            
    fi
    lxc_ip=$(sudo -s lxc-info -n $lxc_name --ip | cut -d ":" -f2)
    i=$[$i+1]
done

if [ -z "$lxc_ip" ]
then    
    echo 'ERROR: No assigned IP to container '$lxc_name''            
fi
sudo -s lxc-attach -n $lxc_name -- passwd ubuntu
