#!/bin/bash

#================= General interfaces ==================
local_if_name=eth0
local_ip_net=10.0.3.1
#=======================================================

#================== CU/DU parameters ===================
du_if_name=$local_if_name:1
du_ip=10.0.20.20
cu_ip=10.0.20.10 
local_n_portc=50000;
remote_n_portc=50001;
local_n_portd=50010;
remote_n_portd=50011;
#=======================================================

#================== TX/RX parameters ===================
bands=[7]
max_rxgain=115
#=======================================================

