#!/bin/bash
#installing lxc
#stty -echo
#read -p "Password: " pass
#stty echo
#echo $pass | sudo -S apt update

source du_params
lxc_name=DU
local_s_address=10.0.3.10

PREFIX_LOCAL='/home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/CU_DU_L2_nFAPI/DU/du_params'
PREFIX_REMOTE='/home/lyapunov_crna/Documents/PhD_5G/Experiments/OAI/CU_DU_L2_nFAPI/CU/cu_params'
PREFIX_NET='/etc/lxc/dnsmasq.conf'
PREFIX_FS='/var/lib/lxc/'$lxc_name'/rootfs/'
PREFIX_HOME='/var/lib/lxc/DU/rootfs/home/ubuntu'
clone_url='https://www.dropbox.com/s/md2fm7b24pinzv8/DU.tar.gz?dl=0'

#echo dhcp-host=$lxc_name','$local_s_address | sudo tee -a $PREFIX_NET

grep -q $lxc_name $PREFIX_NET  && sudo -s sed -i '/'$lxc_name'/c\dhcp-host='$lxc_name','$local_s_address'' $PREFIX_NET  || echo 'dhcp-host='$lxc_name','$local_s_address'' | sudo tee -a $PREFIX_NET
sudo service lxc-net restart
sudo service lxc restart
sudo /etc/init.d/dnsmasq restart


sudo lxc-create -t download -n $lxc_name -- -d ubuntu -r bionic -a amd64

sudo -s  wget -O $PREFIX_HOME/DU.tar.gz $clone_url
sudo -s tar -xzf $PREFIX_HOME/DU.tar.gz -C $PREFIX_HOME
sudo service lxc-net restart
sudo service lxc restart
sudo /etc/init.d/dnsmasq restart


#sudo lxc-start -n $lxc_name -d


#sudo lxc-attach -n $lxc_name -- passwd ubuntu



#if [ -z "$lxc_ip" ] then
#    i="0"
#    while [ $i -lt 5 ] 
#   do
#        lxc_ip=$(lxc-info -n $lxc_name --ip | cut -d ":" -f2)
#        i=$[$i+1]
        #if [ -z "$lxc_ip" ] then
        #    echo $lxc_ip
        #    #break            
        #fi
#    done
    #echo "\$lxc_ip is empty"
#fi
#echo $a
#echo local_s_address=$a | tee -a cu_params
#echo dhcp-host=$lxc_name','$local_s_address | sudo tee -a $PREFIX_NET
#sudo service lxc-net restart
#sudo service lxc restart
#sudo /etc/init.d/dnsmasq restart

#echo $pass | sudo -S lxc-create -t download -n $lxc_name -- -d ubuntu -r bionic -a amd64



#grep -q $lxc_name $PREFIX_NET  && sudo -s sed -i '/'$lxc_name'/c\dhcp-host='$lxc_name','$local_s_address'' $PREFIX_NET  || echo 'dhcp-host='$lxc_name','$local_s_address'' | sudo tee -a $PREFIX_NET


#sudo -s  wget -O $PREFIX_HOME/CU.tar.gz $clone_url
#sudo -s tar -xzf $PREFIX_HOME/CU.tar.gz -C $PREFIX_HOME

#lxc-start -n $lxc_name -d
#lxc-attach -n $lxc_name -- passwd ubuntu
#lxc-stop -n $lxc_name 
  
#sudo service lxc-net restart
#sudo service lxc restart  
#sudo /etc/init.d/dnsmasq restart


#sudo -s chroot $PREFIX_FS passwd  ubuntu 
#sudo lxc-console -n nFAPI_CU
#sudo lxc-start -n nFAPI_CU -d






